# -*- coding: utf-8 -*-
"""chipo1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1STCpogp-WRMHeQIWQi5LHcH1JV3mRCsO
"""

import pandas as pd
import numpy as np

url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
    
chipo = pd.read_csv(url, sep = '\t')

chipo.head(10)

chipo.shape[0]

chipo.info()

chipo.shape[1]

chipo.columns

chipo.index

c= chipo.groupby('item_name')
c=c.sum()
c=c.sort_values(['quantity'],ascending=False)
c.head(1)

c=chipo.groupby('item_name')
c=c.sum()
c=c.sort_values(['quantity'],ascending=False)
c.head(1)

c=chipo.groupby('choice_description').sum()
c=c.sort_values(['quantity'],ascending=False)
c.head(1)

total_items_orders=chipo.quantity.sum()
total_items_orders

chipo.item_price.dtype

dollarizer=lambda x : float(x[1:-1])
chipo.item_price=chipo.item_price.apply(dollarizer)

revenue = (chipo['quantity']*chipo['item_price']).sum()
print('Revenue was : $'+str(np.round(revenue,2)))

orders=chipo.order_id.value_counts().count()
orders

chipo.columns

chipo['revenue']=chipo['quantity']*chipo['item_price']
order_grouped=chipo.groupby(by=['order_id']).sum()
order_grouped.mean()['revenue']

chipo.groupby('order_id').sum().mean()['revenue']

users = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user', 
                      sep='|', index_col='user_id')

users.head(25)

users.tail(10)

users.shape[0]

users.shape[1]

users.index

users.occupation.nunique()

users.occupation.index[0]

users.describe()

users.describe(include = "all")

users.occupation.describe()

users.age.mean()

users.age.value_counts().tail()